name: quran_tracing
description: تطبيق نسخ القرآن الكريم بالقلم - مصحف المدينة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  perfect_freehand: ^2.0.3
  flutter_svg: ^2.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/001.svg
